-- ManagePEC - Physical Education Centre database schema (MySQL 8 / MariaDB 10.4+)
--
-- Table names, column names and constraints match schema.sqlite.sql exactly.
-- Change both files together.
--
-- Create the database first:
--   CREATE DATABASE PEC CHARACTER SET utf8mb4;
--   USE PEC;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS EQUIPMENT_REGISTRATION;
DROP TABLE IF EXISTS EQUIPMENT_MAINTENANCE;
DROP TABLE IF EXISTS EQUIPMENT_FUNDS;
DROP TABLE IF EXISTS FUNDS;
DROP TABLE IF EXISTS EQUIPMENT;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS FITNESS_CHALLENGE_WINNERS;
DROP TABLE IF EXISTS FITNESS_CHALLENGE_MENTORS;
DROP TABLE IF EXISTS FITNESS_SECTIONS_DETAILS;
DROP TABLE IF EXISTS FITNESS_SECTIONS;
DROP TABLE IF EXISTS FITNESS_CHALLENGES_DETAILS;
DROP TABLE IF EXISTS FITNESS_CHALLENGES;
DROP TABLE IF EXISTS MEDICAL_HISTORY_DETAILS;
DROP TABLE IF EXISTS MEDICAL_HISTORY;
DROP TABLE IF EXISTS SPORTS_SLOT;
DROP TABLE IF EXISTS SPORTS_LOCATION;
DROP TABLE IF EXISTS STAFF_TASKS;
DROP TABLE IF EXISTS STAFF_POSITION;
DROP TABLE IF EXISTS STAFF_PROFESSIONAL;
DROP TABLE IF EXISTS STUDENT_HEALTH_DETAILS;
DROP TABLE IF EXISTS STUDENT_SPORT_DETAILS;
DROP TABLE IF EXISTS STUDENT_ACAD_DETAILS;
DROP TABLE IF EXISTS STUDENT_PERSONAL_DETAILS;
DROP TABLE IF EXISTS STAFF_DETAILS;
DROP TABLE IF EXISTS SPORTS;

SET FOREIGN_KEY_CHECKS = 1;

-- ---------------------------------------------------------------- core people

CREATE TABLE STUDENT_PERSONAL_DETAILS (
  Student_ID    INT         NOT NULL,
  First_Name    VARCHAR(50) NOT NULL,
  Last_Name     VARCHAR(50) NOT NULL,
  Date_of_Birth DATE        NOT NULL,
  Contact       VARCHAR(15) NOT NULL,
  PRIMARY KEY (Student_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE STAFF_DETAILS (
  Staff_ID   INT         NOT NULL,
  First_Name VARCHAR(50) NOT NULL,
  Last_Name  VARCHAR(50) NOT NULL,
  Contact    VARCHAR(15) NOT NULL,
  PRIMARY KEY (Staff_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------------------- sports

CREATE TABLE SPORTS (
  Sport_ID           INT          NOT NULL,
  Sport_Name         VARCHAR(50)  NOT NULL,
  Capacity           INT          NOT NULL,
  No_of_Participants INT          NOT NULL DEFAULT 0,
  Rules_Link         VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (Sport_ID),
  KEY IDX_SPORTS_NAME (Sport_Name),
  CONSTRAINT CHK_SPORTS_CAPACITY CHECK (Capacity > 0),
  CONSTRAINT CHK_SPORTS_PARTICIPANTS CHECK (No_of_Participants >= 0 AND No_of_Participants <= Capacity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SPORTS_LOCATION (
  Sport_ID INT         NOT NULL,
  Trainer  INT         DEFAULT NULL,
  Location VARCHAR(50) NOT NULL,
  PRIMARY KEY (Sport_ID),
  KEY IDX_SPORTS_LOCATION_TRAINER (Trainer),
  CONSTRAINT FK_SPORTS_LOCATION_SPORT FOREIGN KEY (Sport_ID) REFERENCES SPORTS (Sport_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SPORTS_LOCATION_TRAINER FOREIGN KEY (Trainer) REFERENCES STAFF_DETAILS (Staff_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A student may hold more than one slot, so the key is the whole booking and
-- not just Student_ID as in the phase-4 dump.
CREATE TABLE SPORTS_SLOT (
  Sport_ID   INT        NOT NULL,
  Student_ID INT        NOT NULL,
  Day        VARCHAR(5) NOT NULL,
  Time       TIME       NOT NULL,
  PRIMARY KEY (Student_ID, Sport_ID, Day, Time),
  KEY IDX_SPORTS_SLOT_SPORT (Sport_ID),
  KEY IDX_SPORTS_SLOT_DAY (Day),
  CONSTRAINT FK_SPORTS_SLOT_SPORT FOREIGN KEY (Sport_ID) REFERENCES SPORTS (Sport_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SPORTS_SLOT_STUDENT FOREIGN KEY (Student_ID) REFERENCES STUDENT_PERSONAL_DETAILS (Student_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------ student details

CREATE TABLE STUDENT_ACAD_DETAILS (
  Student_ID   INT         NOT NULL,
  Department   VARCHAR(50) NOT NULL,
  Course_Year  VARCHAR(50) NOT NULL,
  Credits_Done INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (Student_ID),
  CONSTRAINT FK_STUDENT_ACAD_STUDENT FOREIGN KEY (Student_ID) REFERENCES STUDENT_PERSONAL_DETAILS (Student_ID) ON DELETE CASCADE,
  CONSTRAINT CHK_STUDENT_CREDITS CHECK (Credits_Done >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Assigned_Sport is nullable and set to NULL when a sport is retired, so the
-- student record survives.  The phase-4 dump cascaded here, which deleted the
-- student outright.
CREATE TABLE STUDENT_SPORT_DETAILS (
  Student_ID     INT NOT NULL,
  Assigned_Sport INT DEFAULT NULL,
  Attendance     INT NOT NULL DEFAULT 0,
  PRIMARY KEY (Student_ID),
  KEY IDX_STUDENT_SPORT (Assigned_Sport),
  CONSTRAINT FK_STUDENT_SPORT_STUDENT FOREIGN KEY (Student_ID) REFERENCES STUDENT_PERSONAL_DETAILS (Student_ID) ON DELETE CASCADE,
  CONSTRAINT FK_STUDENT_SPORT_SPORT FOREIGN KEY (Assigned_Sport) REFERENCES SPORTS (Sport_ID) ON DELETE SET NULL,
  CONSTRAINT CHK_STUDENT_ATTENDANCE CHECK (Attendance BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE STUDENT_HEALTH_DETAILS (
  Student_ID   INT          NOT NULL,
  Health_Issue VARCHAR(100) NOT NULL,
  PRIMARY KEY (Student_ID),
  CONSTRAINT FK_STUDENT_HEALTH_STUDENT FOREIGN KEY (Student_ID) REFERENCES STUDENT_PERSONAL_DETAILS (Student_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -------------------------------------------------------------- staff details

CREATE TABLE STAFF_PROFESSIONAL (
  Staff_ID       INT         NOT NULL,
  Join_Date      DATE        NOT NULL,
  Type           VARCHAR(50) NOT NULL,
  Total_Salary   INT         NOT NULL,
  Pending_Salary INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (Staff_ID),
  CONSTRAINT FK_STAFF_PROF_STAFF FOREIGN KEY (Staff_ID) REFERENCES STAFF_DETAILS (Staff_ID) ON DELETE CASCADE,
  CONSTRAINT CHK_STAFF_SALARY CHECK (Total_Salary >= 0 AND Pending_Salary >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE STAFF_POSITION (
  Staff_ID   INT         NOT NULL,
  Sport_ID   INT         DEFAULT NULL,
  Position   VARCHAR(50) NOT NULL,
  Supervisor INT         DEFAULT NULL,
  PRIMARY KEY (Staff_ID),
  KEY IDX_STAFF_POSITION_SPORT (Sport_ID),
  KEY IDX_STAFF_POSITION_SUPERVISOR (Supervisor),
  CONSTRAINT FK_STAFF_POSITION_STAFF FOREIGN KEY (Staff_ID) REFERENCES STAFF_DETAILS (Staff_ID) ON DELETE CASCADE,
  CONSTRAINT FK_STAFF_POSITION_SPORT FOREIGN KEY (Sport_ID) REFERENCES SPORTS (Sport_ID) ON DELETE SET NULL,
  CONSTRAINT FK_STAFF_POSITION_SUPERVISOR FOREIGN KEY (Supervisor) REFERENCES STAFF_DETAILS (Staff_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- One row per scheduled piece of work, not one row per member of staff.
CREATE TABLE STAFF_TASKS (
  Staff_ID INT          NOT NULL,
  Day      DATE         NOT NULL,
  Time     TIME         NOT NULL,
  Work     VARCHAR(100) NOT NULL,
  PRIMARY KEY (Staff_ID, Day, Time),
  CONSTRAINT FK_STAFF_TASKS_STAFF FOREIGN KEY (Staff_ID) REFERENCES STAFF_DETAILS (Staff_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------- fitness challenges

CREATE TABLE FITNESS_CHALLENGES (
  Challenge_ID   INT         NOT NULL,
  Challenge_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (Challenge_ID),
  KEY IDX_CHALLENGE_NAME (Challenge_Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FITNESS_CHALLENGES_DETAILS (
  Challenge_ID          INT  NOT NULL,
  From_Date             DATE NOT NULL,
  To_Date               DATE NOT NULL,
  Registration_Deadline DATE NOT NULL,
  PRIMARY KEY (Challenge_ID),
  CONSTRAINT FK_CHALLENGE_DETAILS_CHALLENGE FOREIGN KEY (Challenge_ID) REFERENCES FITNESS_CHALLENGES (Challenge_ID) ON DELETE CASCADE,
  CONSTRAINT CHK_CHALLENGE_DATES CHECK (To_Date >= From_Date AND Registration_Deadline <= From_Date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FITNESS_SECTIONS (
  CS_REF_ID    INT         NOT NULL,
  Challenge_ID INT         DEFAULT NULL,
  Section_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (CS_REF_ID),
  KEY IDX_SECTIONS_CHALLENGE (Challenge_ID),
  CONSTRAINT FK_SECTIONS_CHALLENGE FOREIGN KEY (Challenge_ID) REFERENCES FITNESS_CHALLENGES (Challenge_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FITNESS_SECTIONS_DETAILS (
  CS_REF_ID INT         NOT NULL,
  Date      DATE        NOT NULL,
  Location  VARCHAR(50) NOT NULL,
  PRIMARY KEY (CS_REF_ID),
  CONSTRAINT FK_SECTION_DETAILS_SECTION FOREIGN KEY (CS_REF_ID) REFERENCES FITNESS_SECTIONS (CS_REF_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A section can be run by several mentors and can have several winners, so both
-- of these are many-to-many bridges rather than one row per section.
CREATE TABLE FITNESS_CHALLENGE_MENTORS (
  CS_REF_ID INT NOT NULL,
  Mentor_ID INT NOT NULL,
  PRIMARY KEY (CS_REF_ID, Mentor_ID),
  KEY IDX_MENTORS_MENTOR (Mentor_ID),
  CONSTRAINT FK_MENTORS_SECTION FOREIGN KEY (CS_REF_ID) REFERENCES FITNESS_SECTIONS (CS_REF_ID) ON DELETE CASCADE,
  CONSTRAINT FK_MENTORS_STAFF FOREIGN KEY (Mentor_ID) REFERENCES STAFF_DETAILS (Staff_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FITNESS_CHALLENGE_WINNERS (
  CS_REF_ID INT         NOT NULL,
  Winner_ID INT         NOT NULL,
  Prize     VARCHAR(50) NOT NULL,
  PRIMARY KEY (CS_REF_ID, Winner_ID),
  KEY IDX_WINNERS_WINNER (Winner_ID),
  CONSTRAINT FK_WINNERS_SECTION FOREIGN KEY (CS_REF_ID) REFERENCES FITNESS_SECTIONS (CS_REF_ID) ON DELETE CASCADE,
  CONSTRAINT FK_WINNERS_STUDENT FOREIGN KEY (Winner_ID) REFERENCES STUDENT_PERSONAL_DETAILS (Student_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -------------------------------------------------------------------- medical

CREATE TABLE MEDICAL_HISTORY (
  Med_ID     INT          NOT NULL,
  Student_ID INT          DEFAULT NULL,
  DateTime   DATETIME     NOT NULL,
  Type       VARCHAR(100) NOT NULL,
  PRIMARY KEY (Med_ID),
  KEY IDX_MEDICAL_STUDENT (Student_ID),
  CONSTRAINT FK_MEDICAL_STUDENT FOREIGN KEY (Student_ID) REFERENCES STUDENT_PERSONAL_DETAILS (Student_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MEDICAL_HISTORY_DETAILS (
  Med_ID    INT          NOT NULL,
  Severity  VARCHAR(50)  NOT NULL,
  Recovery  DATE         NOT NULL,
  Treatment VARCHAR(250) NOT NULL,
  PRIMARY KEY (Med_ID),
  CONSTRAINT FK_MEDICAL_DETAILS_MEDICAL FOREIGN KEY (Med_ID) REFERENCES MEDICAL_HISTORY (Med_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------- money and equipment

CREATE TABLE TRANSACTIONS (
  Transaction_ID INT         NOT NULL,
  Amount         INT         NOT NULL,
  Status         VARCHAR(50) NOT NULL,
  PRIMARY KEY (Transaction_ID),
  CONSTRAINT CHK_TRANSACTION_AMOUNT CHECK (Amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FUNDS (
  Fund_ID        INT  NOT NULL,
  Transaction_ID INT  DEFAULT NULL,
  Date           DATE NOT NULL,
  PRIMARY KEY (Fund_ID),
  KEY IDX_FUNDS_TRANSACTION (Transaction_ID),
  KEY IDX_FUNDS_DATE (Date),
  CONSTRAINT FK_FUNDS_TRANSACTION FOREIGN KEY (Transaction_ID) REFERENCES TRANSACTIONS (Transaction_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EQUIPMENT (
  Equipment_ID   INT         NOT NULL,
  Equipment_Name VARCHAR(50) NOT NULL,
  Sport_ID       INT         DEFAULT NULL,
  Quantity       INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (Equipment_ID),
  KEY IDX_EQUIPMENT_SPORT (Sport_ID),
  CONSTRAINT FK_EQUIPMENT_SPORT FOREIGN KEY (Sport_ID) REFERENCES SPORTS (Sport_ID) ON DELETE SET NULL,
  CONSTRAINT CHK_EQUIPMENT_QUANTITY CHECK (Quantity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EQUIPMENT_FUNDS (
  Transaction_ID INT NOT NULL,
  Equipment_ID   INT DEFAULT NULL,
  Quantity       INT NOT NULL,
  PRIMARY KEY (Transaction_ID),
  KEY IDX_EQUIPMENT_FUNDS_EQUIPMENT (Equipment_ID),
  CONSTRAINT FK_EQUIPMENT_FUNDS_TRANSACTION FOREIGN KEY (Transaction_ID) REFERENCES TRANSACTIONS (Transaction_ID) ON DELETE CASCADE,
  CONSTRAINT FK_EQUIPMENT_FUNDS_EQUIPMENT FOREIGN KEY (Equipment_ID) REFERENCES EQUIPMENT (Equipment_ID) ON DELETE SET NULL,
  CONSTRAINT CHK_EQUIPMENT_FUNDS_QUANTITY CHECK (Quantity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EQUIPMENT_MAINTENANCE (
  Equipment_ID INT         NOT NULL,
  Staff_ID     INT         DEFAULT NULL,
  Date         DATE        NOT NULL,
  Status       VARCHAR(50) NOT NULL,
  PRIMARY KEY (Equipment_ID, Date),
  KEY IDX_EQUIPMENT_MAINT_STAFF (Staff_ID),
  KEY IDX_EQUIPMENT_MAINT_DATE (Date),
  CONSTRAINT FK_EQUIPMENT_MAINT_EQUIPMENT FOREIGN KEY (Equipment_ID) REFERENCES EQUIPMENT (Equipment_ID) ON DELETE CASCADE,
  CONSTRAINT FK_EQUIPMENT_MAINT_STAFF FOREIGN KEY (Staff_ID) REFERENCES STAFF_DETAILS (Staff_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EQUIPMENT_REGISTRATION (
  Registration_ID        INT  NOT NULL,
  Equipment_ID           INT  DEFAULT NULL,
  Fund_ID                INT  DEFAULT NULL,
  Expected_Approval_Date DATE NOT NULL,
  PRIMARY KEY (Registration_ID),
  KEY IDX_EQUIPMENT_REG_EQUIPMENT (Equipment_ID),
  KEY IDX_EQUIPMENT_REG_FUND (Fund_ID),
  CONSTRAINT FK_EQUIPMENT_REG_EQUIPMENT FOREIGN KEY (Equipment_ID) REFERENCES EQUIPMENT (Equipment_ID) ON DELETE CASCADE,
  CONSTRAINT FK_EQUIPMENT_REG_FUND FOREIGN KEY (Fund_ID) REFERENCES FUNDS (Fund_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
